name: Package JSON Change

on:
  workflow_dispatch:
  push:
    paths:
      - "package.json"

env:
  CI: 1

jobs:
  build:
    name: Package json change
    runs-on: macos-13
    strategy:
      matrix:
        xcode_version: [14.3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build native code
        run: npx expo prebuild --clean
